In [1]:
import numpy as np

# Python Package:Numpy

# Initializing the numpy array

In [2]:
a=np.array([8,1,2])
print(type(a))

<class 'numpy.ndarray'>


# Prints the dimension of an array

In [3]:
print(a.shape)

(3,)


In [4]:
print(a[0])

8


In [5]:
print(a[1])

1


# Changes the element of an array

In [6]:
a[0]=9
print(a)

[9 1 2]


# Create a rank 2 array


In [10]:
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)


(2, 3)


In [11]:
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

[[0 1 2]
 [3 4 5]]
0 1 3


# Creates a 4x4 array of all zeros

In [12]:
a=np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Creates a 3x3 array of all ones

In [13]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Creates a 3x3 constant array

In [14]:
c=np.full((3,3),7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# Creates a 3x3 array filled with random values

In [17]:
d=np.random.random((3,3))
print(d)

[[0.24312855 0.46986416 0.18374271]
 [0.07856078 0.21226483 0.21523444]
 [0.71245532 0.53967541 0.41828875]]


# Creates a 3x3 identity matrix

In [20]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Convert list to an array

In [21]:
f=np.array([1,2,3,4])
print(f)

[1 2 3 4]


# arange() will create arrays with regularly incrementing values

In [22]:
g=np.arange(2,10)
print(g)

[2 3 4 5 6 7 8 9]


# Mix of tuple and list

In [24]:
h = np.array([[0,1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


# Create an array of range with float datatype

In [25]:
i=np.arange(1,8,dtype=np.float)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


# linspace() will create arrays with a specified number of items which are spaced equally between the specified beginning and end values


In [29]:
j=np.linspace(2.,4.,5)
print(j)

[2.  2.5 3.  3.5 4. ]


# indices() will create a set of arrays stacked as a one-higher  dimensioned array, one per dimension with each representing variation in that dimension

In [30]:
k = np.indices((3,3))
print(k)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [31]:
#NumPy datatypes
# Let numpy choose the datatype
x = np.array([0, 1])
y = np.array([2.0, 3.0])
# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)
print(x.dtype, y.dtype, z.dtype)


int32 float64 int64


In [32]:
# Basic slicing : The basic slice syntax is i: j: k, 
# where i is the starting index,j is the stopping index,
# and k is the step and k is not equal to 0.
x = np.array([5, 6, 7, 8, 9])
print(x[1:7:2])
print(x[-2:5])
print(x[-1:1:-1])


[6 8]
[8 9]
[9 8 7]


In [33]:
#Boolean array indexing
a=np.array([[1,2], [3, 4], [5, 6]])
# Find the elements of a that are bigger than 2
print (a > 2)
# to get the actual value
print (a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [34]:
import numpy as np
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8],[9,10],[11,12]])
# Elementwise sum; both produce the array
print(x+y)
print(np.add(x, y))
# Elementwise difference; both produce the array
print(x-y)
print(np.subtract(x, y))


[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [35]:
# Elementwise product; both produce the array
print(x*y)
print(np.multiply(x, y))


[[ 7 16]
 [27 40]
 [55 72]]
[[ 7 16]
 [27 40]
 [55 72]]


In [36]:
print(x/y)
print(np.divide(x, y))

[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]
[[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]


In [37]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [38]:
a=np.array([9,10])
b=np.array([11, 12])
# Inner product of vectors; both produce 219
print(a.dot(b))
print(np.dot(a, b))

219
219


In [39]:
# Matrix / vector product; both produce the rank 1 array [29 67]
x=np.array([[1,2],[3,4]])
print(x.dot(a))
print(np.dot(x, a))

[29 67]
[29 67]


In [40]:
# Matrix / matrix product; both produce the rank 2 array
y=np.array([[5,6],[7,8]])
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [41]:
# Sum function
x=np.array([[1,2],[3,4]])
# Compute sum of all elements
print (np.sum(x))
# Compute sum of each column
print (np.sum(x, axis=0))
# Compute sum of each row
print (np.sum(x, axis=1))

10
[4 6]
[3 7]


In [42]:
#Transpose function
x=np.array([[1,2], [3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [43]:
# Note that taking the transpose of a rank 1 array does nothing:
v=np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


# Broadcasting : Broadcasting enables arithmetic operations to be performed between different shaped arrays



In [44]:
# Broadcasting using NumPy
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])
# Add v to each row of a using broadcasting
b = a + v
print(b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [45]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column
x=np.array([[1,2,1], [3,4,1]])
print("X.T:\n",x.T)
w= np.array([1,1])
print("W:\n",w)

print("Final :\n",(x.T + w).T)


X.T:
 [[1 3]
 [2 4]
 [1 1]]
W:
 [1 1]
Final :
 [[2 3 2]
 [4 5 2]]


In [46]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3)
print(x * 2)


[[2 4 2]
 [6 8 2]]
